# Generated by Django 3.1.4 on 2020-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='backend',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='frontend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
