# Generated by Django 3.1.4 on 2020-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201230_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='backend',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='frontend',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registrado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
