# Generated by Django 3.1.4 on 2020-12-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=32)),
                ('extra', models.TextField(blank=True, null=True)),
                ('exponer_variable', models.IntegerField()),
            ],
            options={
                'db_table': 'accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Acontecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'acontecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=11, null=True)),
                ('activo', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anuncio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOperaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=512, null=True)),
                ('detalles', models.TextField()),
                ('operacion', models.CharField(blank=True, max_length=128, null=True)),
                ('usuario', models.CharField(max_length=390)),
                ('proceso', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'auditoria_operaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('readonly', models.IntegerField()),
                ('valor_default', models.TextField()),
                ('posicion', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=32)),
                ('etiqueta', models.TextField()),
                ('ayuda', models.TextField()),
                ('validacion', models.CharField(max_length=128)),
                ('dependiente_tipo', models.CharField(max_length=7)),
                ('dependiente_campo', models.CharField(blank=True, max_length=64, null=True)),
                ('dependiente_valor', models.CharField(blank=True, max_length=256, null=True)),
                ('datos', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('dependiente_relacion', models.CharField(max_length=2)),
                ('condiciones_extra_visible', models.TextField(blank=True, null=True)),
                ('agenda_campo', models.BigIntegerField(blank=True, null=True)),
                ('exponer_campo', models.IntegerField()),
            ],
            options={
                'db_table': 'campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=256)),
                ('icon_ref', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaContinuarTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_id', models.IntegerField(blank=True, null=True)),
                ('tarea_id', models.IntegerField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('procesado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cola_continuar_tramite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=19)),
                ('regla', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'conexion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpar', models.PositiveIntegerField()),
                ('endpoint', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_visible', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigGeneral',
            fields=[
                ('componente', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cuenta', models.IntegerField()),
                ('llave', models.CharField(max_length=80)),
                ('valor', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'config_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('nombre_largo', models.CharField(max_length=256)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('mensaje', models.TextField()),
                ('logo', models.CharField(blank=True, max_length=128, null=True)),
                ('logof', models.CharField(blank=True, max_length=128, null=True)),
                ('favicon', models.CharField(blank=True, max_length=128, null=True)),
                ('api_token', models.CharField(blank=True, max_length=32, null=True)),
                ('descarga_masiva', models.IntegerField()),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('ambiente', models.CharField(max_length=255)),
                ('vinculo_produccion', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, max_length=256, null=True)),
                ('estilo', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=64)),
                ('footer', models.CharField(max_length=64)),
                ('personalizacion', models.TextField(blank=True, null=True)),
                ('personalizacion_estado', models.CharField(max_length=1)),
                ('seo_tags', models.CharField(blank=True, max_length=4096, null=True)),
                ('analytics', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaHasConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpar', models.PositiveIntegerField()),
                ('config_id', models.PositiveIntegerField()),
                ('cuenta_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cuenta_has_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatoSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('valor', models.TextField()),
            ],
            options={
                'db_table': 'dato_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=128)),
                ('contenido', models.TextField()),
                ('servicio', models.CharField(max_length=128)),
                ('servicio_url', models.CharField(max_length=128)),
                ('logo', models.CharField(max_length=256)),
                ('timbre', models.CharField(max_length=256)),
                ('sello_agua', models.CharField(blank=True, max_length=255, null=True)),
                ('firmador_nombre', models.CharField(max_length=128)),
                ('firmador_cargo', models.CharField(max_length=128)),
                ('firmador_servicio', models.CharField(max_length=128)),
                ('firmador_imagen', models.CharField(max_length=256)),
                ('validez', models.PositiveIntegerField(blank=True, null=True)),
                ('subtitulo', models.CharField(max_length=128)),
                ('titulo', models.CharField(max_length=128)),
                ('validez_habiles', models.IntegerField(blank=True, null=True)),
                ('tamano', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.IntegerField()),
                ('vencimiento_at', models.DateField(blank=True, null=True)),
                ('vencimiento_avance', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(blank=True, max_length=512, null=True)),
                ('instante', models.CharField(max_length=7)),
                ('campo_asociado', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('metodo', models.CharField(blank=True, max_length=4, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('regla', models.TextField(blank=True, null=True)),
                ('opciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'failed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'feriado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=9, null=True)),
                ('llave', models.CharField(max_length=12)),
                ('llave_copia', models.CharField(blank=True, max_length=40, null=True)),
                ('llave_firma', models.CharField(blank=True, max_length=12, null=True)),
                ('validez', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('validez_habiles', models.IntegerField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('campo_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'grupo_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_modificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HsmConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('entidad', models.CharField(blank=True, max_length=256, null=True)),
                ('proposito', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'hsm_configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=8)),
                ('extra', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('filepath', models.CharField(blank=True, max_length=255, null=True)),
                ('arguments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('downloads', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginErroneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128)),
                ('horario', models.DateTimeField()),
            ],
            options={
                'db_table': 'login_erroneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajeBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensaje_backend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('modo', models.CharField(max_length=13)),
                ('regla', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'paso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre_frontend', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_rnt', models.CharField(blank=True, max_length=128, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_informativa', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
                ('proc_cont', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('categoria_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('icon_ref', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('root', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('concurrente', models.IntegerField(blank=True, null=True)),
                ('eliminar_tramites', models.IntegerField(blank=True, null=True)),
                ('ocultar_front', models.IntegerField(blank=True, null=True)),
                ('ficha_informativa', models.IntegerField()),
                ('ficha_titulo', models.CharField(blank=True, max_length=128, null=True)),
                ('ficha_contenido', models.TextField(blank=True, null=True)),
                ('descarga_documentos', models.IntegerField()),
            ],
            options={
                'db_table': 'proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuenta_origen', models.IntegerField(blank=True, null=True)),
                ('id_cuenta_destino', models.IntegerField(blank=True, null=True)),
                ('id_proceso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proceso_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('campos', models.TextField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=128, null=True)),
                ('servicio', models.CharField(blank=True, max_length=128, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('proceso_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seguridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=128, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('proceso_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suscriptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=32)),
                ('inicial', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('posx', models.PositiveIntegerField()),
                ('posy', models.PositiveIntegerField()),
                ('asignacion', models.CharField(max_length=12)),
                ('asignacion_usuario', models.CharField(blank=True, max_length=128, null=True)),
                ('asignacion_notificar', models.IntegerField()),
                ('almacenar_usuario', models.IntegerField()),
                ('almacenar_usuario_variable', models.CharField(blank=True, max_length=128, null=True)),
                ('acceso_modo', models.CharField(max_length=15)),
                ('activacion', models.CharField(max_length=12)),
                ('activacion_inicio', models.DateField(blank=True, null=True)),
                ('activacion_fin', models.DateField(blank=True, null=True)),
                ('vencimiento', models.IntegerField()),
                ('vencimiento_valor', models.CharField(max_length=128)),
                ('vencimiento_unidad', models.CharField(max_length=1)),
                ('vencimiento_habiles', models.IntegerField()),
                ('vencimiento_notificar', models.IntegerField()),
                ('vencimiento_notificar_email', models.CharField(blank=True, max_length=255, null=True)),
                ('vencimiento_notificar_dias', models.PositiveIntegerField()),
                ('grupos_usuarios', models.TextField(blank=True, null=True)),
                ('paso_confirmacion', models.IntegerField()),
                ('paso_confirmacion_titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('paso_confirmacion_contenido', models.TextField(blank=True, null=True)),
                ('paso_confirmacion_texto_boton_final', models.CharField(blank=True, max_length=255, null=True)),
                ('previsualizacion', models.TextField(blank=True, null=True)),
                ('externa', models.IntegerField()),
                ('es_final', models.IntegerField()),
                ('exponer_tramite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('tramite_proc_cont', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tramite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUserprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=200)),
                ('registrado', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('img_perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('backend', models.IntegerField()),
                ('frontend', models.IntegerField()),
            ],
            options={
                'db_table': 'users_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('rut', models.CharField(blank=True, max_length=16, null=True)),
                ('nombres', models.CharField(blank=True, max_length=128, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=128, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('registrado', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('open_id', models.IntegerField()),
                ('reset_token', models.CharField(blank=True, max_length=40, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('rol', models.CharField(blank=True, max_length=150, null=True)),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=40, null=True)),
                ('procesos', models.CharField(blank=True, max_length=150, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('acepta_terminos', models.IntegerField(blank=True, null=True)),
                ('fecha_aceptacion_terminos', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_backend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('email', models.TextField(blank=True, null=True)),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=128)),
                ('posicion', models.PositiveIntegerField()),
                ('config', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'widget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuariosHasUsuario',
            fields=[
                ('grupo_usuarios', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='simpleDos.grupousuarios')),
            ],
            options={
                'db_table': 'grupo_usuarios_has_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaHasGrupoUsuarios',
            fields=[
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='simpleDos.tarea')),
            ],
            options={
                'db_table': 'tarea_has_grupo_usuarios',
                'managed': False,
            },
        ),
    ]
